#ifndef TRANSFERCMD_GLOBAL_H
#define TRANSFERCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSFERCMD_LIBRARY)
#  define TRANSFERCMDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRANSFERCMDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSFERCMD_GLOBAL_H
