#ifndef RECEIVEDISPLAYFRAME_GLOBAL_H
#define RECEIVEDISPLAYFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RECEIVEDISPLAYFRAME_LIBRARY)
#  define RECEIVEDISPLAYFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define RECEIVEDISPLAYFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RECEIVEDISPLAYFRAME_GLOBAL_H
