#ifndef CONTROLPROTOCOL_GLOBAL_H
#define CONTROLPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLPROTOCOL_LIBRARY)
#  define CONTROLPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLPROTOCOL_GLOBAL_H
