#ifndef CAPTURESENDFRAME_GLOBAL_H
#define CAPTURESENDFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAPTURESENDFRAME_LIBRARY)
#  define CAPTURESENDFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAPTURESENDFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAPTURESENDFRAME_GLOBAL_H
