#ifndef TRANSFERFRAME_GLOBAL_H
#define TRANSFERFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSFERFRAME_LIBRARY)
#  define TRANSFERFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRANSFERFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSFERFRAME_GLOBAL_H
